#!/usr/bin/env zsh

usage="
Usage: $0 < file-to-fix.srt > fixed.srt

Inserts missing newlines in single line srt file
"

if [[ $1 =~ "-?-h.*" ]]; then
  echo "$usage"
  return 1
fi

if (( $+commands[gsed] )); then
  sed_command=gsed
else
  sed_command=sed
fi

$sed_command -E 's/([0-9]+) ([0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})/\1\
\2/g; s/([0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} --> [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}) /\1\
/g; s/ ([0-9]+)\
([0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})/\
\
\1\
\2/g'
